run-name: "Generate docs"

name: "Generate docs"

on: [push]

jobs:
  build_docs:
    runs-on: ubuntu-latest

    permissions:
      conents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pdoc
      run: pip install pdoc

    - name: Generate documentation
      run: pdoc pychord --output-dir docs

    - uses: stefanzweifel/git-auto-commit-action@v4
